name: GitHub GraphQL API Query
description: "Send queries to GitHub's GraphQL API"
branding:
  icon: "box"
  color: gray-dark
inputs:
  query:
    description: "Your GraphQL query, see https://developer.github.com/v4/"
    required: true
  previews:
    description: A comma-separated list of API previews to accept
outputs:
  data:
    description: 'The "data" key of the GraphQL response body'
runs:
  using: "node16"
  main: "dist/index.js"
