name: GitHub GraphQL API Query
description: "Send queries to GitHub's GraphQL API"
branding:
  icon: "box"
  color: gray-dark
inputs:
  query:
    description: "Your GraphQL query, see https://developer.github.com/v4/"
    required: true
  mediaType:
    description: "Enable previews - see https://github.com/octokit/graphql-action/blob/main/README.md#preview-media-types"
  variables:
    description: "Variables described in YAML"
outputs:
  data:
    description: 'The "data" key of the GraphQL response body'
runs:
  using: "node16"
  main: "dist/index.js"
